version: "3"
services: 
  api-gateway:
    container_name: api-gateway
    build: ./BE_baemin_microservice/api-gateway 
    ports:
      - 8080:8080
    networks:
      - node-network
    depends_on:
      - rabbitmq
      - redis

  identity-service:
    container_name: identity-service
    build: ./BE_baemin_microservice/identity-service
    networks:
      - node-network
    depends_on:
      - rabbitmq

  notification-service:
    container_name: notification-service
    build: ./BE_baemin_microservice/notification-service 
    networks:
      - node-network
    depends_on:
      - rabbitmq

  payment-service:
    container_name: payment-service
    build: ./BE_baemin_microservice/payment-service
    networks:
      - node-network
    depends_on:
      - rabbitmq
      - redis

  product-service:
    container_name: product-service
    build: ./BE_baemin_microservice/product-service
    networks:
      - node-network
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: some-rabbit
    image: rabbitmq:3-management
    ports:
      - 15672:15672  
      - 5672:5672    
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
    networks:
      - node-network

  redis:
    container_name: some-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - node-network

  postgres:
    image: postgres:latest
    container_name: some-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_baemin 
    ports:
      - "5432:5432"
    networks:
      - node-network
    volumes:
      - ./db_baemin.dump:/docker-entrypoint-initdb.d/db_baemin.dump # Mount file dump vào thư mục init

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - node-network

  kibana:
    container_name: kibana
    image: kibana:8.15.0
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_NODE=http://elasticsearch:9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASS=JZ9n2yb*zN54q6Ta=Ho=
    ports:
      - 5601:5601
    networks:
      - node-network

  logstash:
    container_name: logstash
    image: logstash:8.15.0
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - 5044:5044  
    networks:
      - node-network
    volumes:
      - ./BE_baemin_microservice/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /usr/share/logstash/driver:/usr/share/logstash/driver
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m

networks:
  node-network:
    external: true # sử dụng mạng có sẵn trước đó

# docker-compose up -d