import HeaderNav from "@/components/headerNav";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import "./globals.css";
import { UserProvider } from "./context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Baemin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <CartProvider>
        <html lang="en">

          <body className="w-full h-fit">

            <HeaderNav />
            <AntdRegistry>{children}
            </AntdRegistry>

          </body>

        </html>
      </CartProvider>
    </UserProvider>
  );
}
